ALTER TABLE members ADD COLUMN IF NOT EXISTS address_line1 TEXT;
ALTER TABLE members ADD COLUMN IF NOT EXISTS address_line2 TEXT;
ALTER TABLE members ADD COLUMN IF NOT EXISTS city TEXT;
ALTER TABLE members ADD COLUMN IF NOT EXISTS state TEXT;
ALTER TABLE members ADD COLUMN IF NOT EXISTS postal_code TEXT;
ALTER TABLE members ADD COLUMN IF NOT EXISTS communication_preference TEXT DEFAULT 'Email';
ALTER TABLE members ADD COLUMN IF NOT EXISTS paperless BOOLEAN DEFAULT TRUE;
ALTER TABLE members ADD COLUMN IF NOT EXISTS refill_reminders BOOLEAN DEFAULT TRUE;
ALTER TABLE members ADD COLUMN IF NOT EXISTS order_updates BOOLEAN DEFAULT TRUE;
