ALTER TABLE pharmacies ADD COLUMN IF NOT EXISTS slug TEXT;
ALTER TABLE pharmacies ADD COLUMN IF NOT EXISTS hours_label TEXT;
ALTER TABLE pharmacies ADD COLUMN IF NOT EXISTS distance_label TEXT;
ALTER TABLE pharmacies ADD COLUMN IF NOT EXISTS pickup BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE pharmacies ADD COLUMN IF NOT EXISTS ninety_day_eligible BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE pharmacies ADD COLUMN IF NOT EXISTS drive_thru BOOLEAN NOT NULL DEFAULT FALSE;
CREATE UNIQUE INDEX IF NOT EXISTS pharmacies_slug_key ON pharmacies(slug) WHERE slug IS NOT NULL;
CREATE INDEX IF NOT EXISTS pharmacies_network_status_idx ON pharmacies(network_status);
